---
title: "The Smooth Step: Simple exchangeable hierarchical priors"
output: rmarkdown::html_vignette
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 10,
  out.width = "100%",
  fig.asp = 0.621,
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)
```

```{r setup}
library(bggjphd)
library(tidyverse)
library(progressr)
library(future)
library(bayesplot)
library(GGally)
library(scales)
library(cowplot)
library(kableExtra)
theme_set(theme_half_open())
```


The results for this analysis were obtained by running `ms_smooth()` in parrallel on four cores with four chains each run for 4000 samples. Half of those samples were designated as warm-up and so we have a total of 8000 samples from the posterior.

```{r}
#| eval: false
#| echo: true
n_iter <- 4000
plan(multisession, workers = 4)
with_progress({
  results <- ms_smooth(n_samp = n_iter)
})
plan(sequential)
```


```{r}
if (!file.exists("results.rds")) {
  n_iter <- 4000
  plan(multisession, workers = 4)
  with_progress({
    results <- ms_smooth(n_samp = n_iter)
  })
  plan(sequential)
  write_rds(results, "results.rds")
} else {
  results <- read_rds("results.rds")
  n_iter <- results |> pull(.iteration) |> max()
}
```

# Parameters

## Hyperpriors

```{r}
results |> 
  filter(.iteration > n_iter/2) |> 
  subset_draws(
    "theta", 
  ) |> 
  summarise_draws() |> 
  kable(digits = 3) |> 
  kable_styling(bootstrap_options = c("striped", "hover"))
```

```{r}
results |> 
  filter(.iteration > n_iter/2) |>
  subset_draws("theta") |> 
  mcmc_trace()
```

```{r}
results |> 
  subset_draws("theta[1]") |> 
  as_tibble() |> 
  rename(value = "theta[1]") |> 
  group_by(.chain) |> 
  mutate(accept = 1 * (value != lag(value))) |> 
  ungroup() |> 
  ggplot(aes(.iteration, accept, group = .chain)) +
  geom_smooth(method = "loess", span = 0.3, se = 0)
```


## GEV Parameters

```{r}
if (!file.exists("station_mcmc_ml.rds")) {
  
  plot_dat <- results |> 
    filter(.iteration > n_iter/2) |> 
    subset_draws(
      c("psi", "tau", "phi", "gamma")
    ) |> 
    summarise_draws()
  
  plot_dat |> 
    select(variable, mcmc_mean = mean, mcmc_median = median) |> 
    mutate(station = parse_number(variable),
           variable = str_replace(variable, "\\[.*$", "")) |> 
    inner_join(
      stations,
      by = "station"
    ) |> 
    inner_join(
      station_estimates |> 
        select(station, par) |> 
        unnest(par) |> 
        rename(ml_estimate = par) |> 
        mutate(variable = c("psi", "tau", "phi", "gamma")),
      by = c("station", "variable")
    ) |> 
    select(station, proj_x, proj_y, latitude, longitude, variable, ml_estimate, mcmc_mean) |> 
    write_rds(file = "station_mcmc_ml.rds")
}

plot_dat <- read_rds("station_mcmc_ml.rds")
```


```{r}
plot_dat |> 
  ggplot(aes(ml_estimate, mcmc_mean)) +
  geom_abline(intercept = 0, slope = 1, lty = 2) +
  geom_point() +
  facet_wrap("variable", scales = "free") +
  labs(
    x = "ML Estimate (Max step)",
    y = "Posterior Mean (Smooth step)",
    title = "Comparing estimates from the Max and the Smooth steps"
  )
```

