---
title: "basics"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{basics}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
#| eval: false
library(tidyverse)
library(progressr)
library(future)
library(bayesplot)
# devtools::load_all()
library(bggjphd)
library(GGally)

n_iter <- 2000

plan(multisession, workers = 4)
with_progress({
  start <- Sys.time()
  results <- ms_smooth(n_samp = n_iter)
  stop <- Sys.time()
  
  stop - start
})
```



```{r}
results |> 
  filter(.iteration > n_iter/2) |> 
  subset_draws(
    c("mu_psi", "mu_phi", "mu_tau", "mu_gamma", "theta"), 
  ) |> 
  summarise_draws()
```

```{r}
results |> 
  filter(.iteration > n_iter/2) |> 
  subset_draws() |> 
  summarise_draws() |> 
  arrange(desc(rhat))
```


```{r}
results |> 
  # filter(.iteration > n_iter/2) |> 
  subset_draws("theta") |> 
  mcmc_trace()
```

```{r}
results |> 
  subset_draws("theta[1]") |> 
  as_tibble() |> 
  rename(value = "theta[1]") |> 
  group_by(.chain) |> 
  mutate(accept = 1 * (value != lag(value))) |> 
  ungroup() |> 
  ggplot(aes(.iteration, accept, group = .chain)) +
  geom_smooth(method = "loess", span = 0.3)
```

```{r}
plot_dat <- results |> 
  filter(.iteration > n_iter/2) |> 
  subset_draws(
    c("phi", "psi", "gamma", "tau")
  ) |> 
  summarise_draws()

p <- plot_dat |> 
  mutate(station = parse_number(variable),
         variable = str_replace(variable, "\\[[0-9]+\\]", "")) |> 
  select(station, variable, mean) |> 
  pivot_wider(names_from = variable, values_from = mean) |> 
  select(-station) |> 
  ggpairs()
```

