---
title: "Untitled"
format: html
editor: source
---

```{r}
library(bggjphd)
library(tidyverse)
library(GGally)
```

```{r}
priors <- list(
  "location" = function(x) 0,
  "scale" = function(x) 0,
  "shape" = function(x) 0,
  "trend" = function(x) 0
)


d <- ms_max(priors = priors) |> 
  ungroup() |> 
  select(station, par) |> 
  unnest(par) |> 
  mutate(name = rep(c("psi", "tau", "phi", "gamma"), max(station)) |> 
           factor(levels = c("psi", "tau", "phi", "gamma"))) |> 
  rename(value = par)


d |> 
  ggplot(aes(value)) +
  geom_histogram(bins = 60) +
  facet_wrap("name", scales = "free")
```

```{r}
d |> 
  pivot_wider() |> 
  select(-station) |> 
  ggpairs(progress = F)
```

```{r}
d |> 
  pivot_wider() |> 
  mutate(mu = exp(psi),
         sigma = exp(tau + psi),
         xi = link_shape_inverse(phi),
         delta = link_trend_inverse(gamma)) |> 
  select(-psi, -tau, -phi, -gamma) |> 
  pivot_longer(c(-station)) |> 
  ggplot(aes(value)) +
  geom_histogram(bins = 100) +
  facet_wrap("name", scales = "free")
```

```{r}
d |> 
  pivot_wider() |> 
  mutate(mu = exp(psi),
         sigma = exp(tau + psi),
         xi = link_shape_inverse(phi),
         delta = link_trend_inverse(gamma)) |> 
  select(-psi, -tau, -phi, -gamma) |> 
  select(-station) |> 
  ggpairs(progress = F)
```

```{r}
d |> 
  pivot_wider() |> 
  mutate(mu = exp(psi),
         sigma = exp(tau + psi),
         xi = link_shape_inverse(phi),
         delta = link_trend_inverse(gamma)) |> 
  inner_join(precip,
             by = "station") |> 
  mutate(e = precip - mu * (1 + delta * (year - 1981))) |> 
  arrange(station, e) |> 
  group_by(station) |> 
  mutate(g_tilde = row_number() / (n() + 1),
         g_hat = evd::pgev(q = precip, loc = mu * (1 + delta * (year - 1981)), scale = sigma, shape = unique(xi)),
         error = sum(abs(g_tilde - g_hat))) |> 
  ungroup() |> 
  arrange(desc(error)) |> 
  filter(station %in% unique(station)[1:100]) |> 
  ggplot(aes(g_hat, g_tilde)) +
  geom_abline(intercept = 0, slope = 1, lty = 2) +
  geom_line(aes(group = station), alpha = 0.1)
```

```{r}
#| fig-width: 12
#| out-width: "100%"
p <- d |> 
  pivot_wider() |> 
  mutate(mu = exp(psi),
         sigma = exp(tau),
         xi = link_shape_inverse(phi),
         delta = link_trend_inverse(gamma)) |> 
  inner_join(precip,
             by = "station") |> 
  mutate(e = precip - mu * (1 + delta * (year - 1981))) |> 
  arrange(station, e) |> 
  # filter(xi > 1e-4) |>
  group_by(station) |> 
  mutate(g_tilde = row_number() / (n() + 1),
         g_hat = f_trend(x = precip, t = year,
                         mu0 = mu, sigma = sigma, xi = xi, delta = delta),
         g_hat = evd::pgev(q = precip, loc = mu * (1 + delta * (year - 1981)), scale = sigma, shape = unique(xi)),
         error = sum(abs(g_tilde - g_hat))) |> 
  ungroup() |> 
  distinct(psi, tau, phi, gamma, error) |> 
  filter(psi < 0) |> 
  ggpairs(progress = FALSE)
```
