---
title: "Using a t-copula"
output: rmarkdown::html_vignette
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 10,
  out.width = "100%",
  fig.asp = 0.621,
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)
```

```{r setup}
library(bggjphd)
library(tidyverse)
library(progressr)
library(future)
library(bayesplot)
library(GGally)
library(scales)
library(cowplot)
library(kableExtra)
library(arrow)
library(tictoc)
library(broom)
library(corrr)
library(patchwork)
theme_set(theme_half_open())
```



# Data

```{r}
pgev <- function(y, loc, scale, shape) {
  out <- 1 + shape * (y - loc) / scale
  out <- out ^ (-1/shape)
  out <- exp(-out)
  out
}

# data("twelve_neighbors")

# neighbor_types <- tribble(
#   ~diff_x, ~diff_y, ~type,
#   -2, 0, "ww",
#   -1, -1, "sw",
#   -1, 0, "w",
#   -1, 1, "nw",
#   0, -2, "ss",
#   0, -1, "s",
#   0, 1, "n",
#   0, 2, "nn",
#   1, -1, "se",
#   1, 0, "e",
#   1, 1, "ne",
#   2, 0, "ee"
# )

coef_data <- read_parquet("Data/station_results.parquet") |> 
  select(station, variable, ml_estimate, mcmc_mean) |> 
  pivot_longer(c(ml_estimate, mcmc_mean), names_to = "model_type") |> 
  pivot_wider(names_from = variable, values_from = value) |> 
  mutate(
    mu0 = exp(psi),
    sigma = exp(tau + psi),
    xi = link_shape_inverse(phi),
    delta = link_trend_inverse(gamma)
  ) |> 
  select(station, model_type, mu0:delta)

d <- precip |> 
  inner_join(
    coef_data, 
    multiple = "all",
    by = "station"
  ) |> 
  mutate(
    mu = mu0 * (1 + (year - 1981) * delta),
    p = pgev(precip, mu, sigma, xi)
  ) |> 
  arrange(station, p) |> 
  mutate(
    t_val = qt(p = p, df = 3)
  ) |> 
  select(year, model_type, station, t_val)

dat <- twelve_neighbors |> 
  inner_join(
    d |> 
      rename(y = t_val),
    by = "station",
    multiple = "all"
  ) |> 
  inner_join(
    d |> 
      rename(x = t_val),
    by = c("neighbor" = "station", "year", "model_type"),
    multiple = "all"
  ) |> 
  select(year, model_type, station, neighbor, y, x, type) |> 
  arrange(station, model_type, year, neighbor)
```







# Simultaneous estimation

```{r , eval=FALSE}
#| eval: false
results <- dat |> 
  select(-neighbor) |> 
  pivot_wider(names_from = type, values_from = x) |> 
  group_by(station, model_type) |> 
  group_modify(
    function(data, ...) {
      model_dat <- data |> 
        select(
          -year
        ) |> 
        select(
          where(
            ~ !any(is.na(.x))
          )
        )
      lm(y ~ . - 1, data = model_dat) |> 
        tidy()
    }
  ) |> 
  ungroup()

results |> 
  write_parquet(
    "Data/multivariate.parquet"
  )
```

```{r}
multivariate <- read_parquet("Data/multivariate.parquet")
```


## Mean values

```{r}
plot_dat <- multivariate |> 
  select(station, model_type, type = term, estimate) |> 
  summarise(
    mean = mean(estimate),
    sd = sd(estimate),
    .by = c(type, model_type)
  ) |> 
  inner_join(
    neighbor_types,
    by = "type"
  ) 

max_est <- max(plot_dat$mean, na.rm = T)
min_est <- min(plot_dat$mean, na.rm = T)
scale_size <- max(abs(max_est), abs(min_est), na.rm = T)
limits <- c(-1, 1) * scale_size


plot_dat |> 
  ggplot(aes(diff_x, diff_y, fill = mean)) +
  geom_raster() + 
  scale_fill_distiller(type = "div", palette = "RdBu", limits = limits, direction = 1) +
  facet_wrap("model_type") +
  labs(
    x = NULL,
    y = NULL
  )
```

```{r}
plot_dat |> 
  select(-sd) |> 
  pivot_wider(names_from = model_type, values_from = mean) |> 
  ggplot(aes(mcmc_mean, ml_estimate)) +
  geom_abline(intercept = 0, slope = 1, lty = 2) +
  geom_point() +
  labs(
    x = "Neighour effect from spatial model",
    y = "Neighbour effect from ML model",
    title = "Comparison of neighbour effects in ML and MCMC models"
  )
```


```{r}
plot_dat |> 
  select(-mean) |> 
  pivot_wider(names_from = model_type, values_from = sd) |> 
  ggplot(aes(mcmc_mean, ml_estimate)) +
  geom_abline(intercept = 0, slope = 1, lty = 2) +
  geom_point() +
  labs(
    x = "Neighour effect from spatial model",
    y = "Neighbour effect from ML model",
    title = "Comparison of neighbour effects in ML and MCMC models"
  )
```

```{r}
multivariate |> 
  select(station, model_type, term, estimate) |> 
  pivot_wider(names_from = model_type, values_from = estimate) |> 
  ggplot(aes(mcmc_mean, ml_estimate)) +
  geom_abline(intercept = 0, slope = 1, lty = 2) +
  geom_point() 
```


## Spatial Distribution

### Maximum Likelihood

```{r}
plot_dat <- multivariate |> 
  filter(model_type == "ml_estimate") |> 
  select(station, type = term, estimate) |> 
  inner_join(
    stations,
    by = "station"
  )


max_est <- max(plot_dat$estimate, na.rm = T)
min_est <- min(plot_dat$estimate, na.rm = T)
scale_size <- max(abs(max_est), abs(min_est), na.rm = T)
limits <- c(-1, 1) * scale_size

# plot_dat |>
#   filter(type == "ww") |>
#   ggplot(aes(proj_x, proj_y, fill = estimate)) +
#   geom_raster(interpolate = TRUE) +
#   scale_fill_distiller(type = "div", palette = "RdBu", limits = limits) +
#   facet_wrap("type")

plots <- plot_dat |> 
  mutate(term = type) |> 
  group_by(type) |> 
  group_nest() |> 
  mutate(
    plots = map(data, 
                function(data, ...) {
                  data |> 
                    ggplot(aes(proj_x, proj_y, fill = estimate)) +
                    geom_raster(interpolate = TRUE) +
                    scale_fill_distiller(
                      type = "div",
                      palette = "RdBu",
                      limits = limits,
                      direction = 1
                    ) +
                    facet_wrap("term") +
                    theme_void()
                }
    )
  ) |> 
  select(type, plots) |> 
  pivot_wider(names_from = type, values_from = plots)

layout <- "
##A##
#BCD#
EF#GH
#IJK#
##L##
"


p <- plots$nn[[1]] + 
  plots$nw[[1]] + plots$n[[1]] + plots$ne[[1]] +
  plots$ww[[1]] + plots$w[[1]] + plots$e[[1]] + plots$ee[[1]] +
  plots$sw[[1]] + plots$s[[1]] + plots$se[[1]] +
  plots$ss[[1]] +
  plot_layout(
    design = layout, 
    guides = "collect"
  ) +
  plot_annotation()
p
```

### Spatial Model

```{r}
plot_dat <- multivariate |> 
  filter(model_type == "mcmc_mean") |> 
  select(station, type = term, estimate) |> 
  inner_join(
    stations,
    by = "station"
  )


max_est <- max(plot_dat$estimate, na.rm = T)
min_est <- min(plot_dat$estimate, na.rm = T)
scale_size <- max(abs(max_est), abs(min_est), na.rm = T)
limits <- c(-1, 1) * scale_size

# plot_dat |>
#   filter(type == "ww") |>
#   ggplot(aes(proj_x, proj_y, fill = estimate)) +
#   geom_raster(interpolate = TRUE) +
#   scale_fill_distiller(type = "div", palette = "RdBu", limits = limits) +
#   facet_wrap("type")

plots <- plot_dat |> 
  mutate(term = type) |> 
  group_by(type) |> 
  group_nest() |> 
  mutate(
    plots = map(data, 
                function(data, ...) {
                  data |> 
                    ggplot(aes(proj_x, proj_y, fill = estimate)) +
                    geom_raster(interpolate = TRUE) +
                    scale_fill_distiller(
                      type = "div",
                      palette = "RdBu",
                      limits = limits,
                      direction = 1
                    ) +
                    facet_wrap("term") +
                    theme_void()
                }
    )
  ) |> 
  select(type, plots) |> 
  pivot_wider(names_from = type, values_from = plots)

layout <- "
##A##
#BCD#
EF#GH
#IJK#
##L##
"


p <- plots$nn[[1]] + 
  plots$nw[[1]] + plots$n[[1]] + plots$ne[[1]] +
  plots$ww[[1]] + plots$w[[1]] + plots$e[[1]] + plots$ee[[1]] +
  plots$sw[[1]] + plots$s[[1]] + plots$se[[1]] +
  plots$ss[[1]] +
  plot_layout(
    design = layout, 
    guides = "collect"
  ) +
  plot_annotation()
p
```

## Parameter Correlations

### Maximum Likelihood

```{r}
plot_dat <- multivariate |> 
  filter(model_type == "ml_estimate") |> 
  select(station, type = term, estimate) |> 
  pivot_wider(names_from = type, values_from = estimate) |> 
  ungroup() |> 
  select(-station) |> 
  correlate(method = "pearson", use = "pairwise.complete.obs", quiet = T) |> 
  pivot_longer(c(-term), names_to = "term2", values_to = "correlation") |> 
  inner_join(
    neighbor_types,
    by = c("term2" = "type")
  )

max_cor <- max(plot_dat$correlation, na.rm = T)
min_cor <- min(plot_dat$correlation, na.rm = T)
scale_size <- max(abs(max_cor), abs(min_cor), na.rm = T)
limits <- c(-1, 1) * scale_size




plots <- plot_dat |> 
  mutate(type = term) |> 
  group_by(type) |> 
  group_nest() |> 
  mutate(
    plots = map(data, 
                function(data, ...) {
                  data |> 
                    ggplot(aes(diff_x, diff_y, fill = correlation)) +
                    geom_raster() +
                    # scale_fill_viridis_c(guide = guide_colorbar(), limits = limits) +
                    scale_fill_distiller(
                      type = "div", 
                      palette = "RdBu", 
                      limits = limits,
                      direction = 1
                    ) +
                    facet_wrap("term") +
                    theme_void() 
                }
    )
  ) |> 
  select(type, plots) |> 
  pivot_wider(names_from = type, values_from = plots)


layout <- "
##A##
#BCD#
EF#GH
#IJK#
##L##
"


p <- plots$nn[[1]] + 
  plots$nw[[1]] + plots$n[[1]] + plots$ne[[1]] +
  plots$ww[[1]] + plots$w[[1]] + plots$e[[1]] + plots$ee[[1]] +
  plots$sw[[1]] + plots$s[[1]] + plots$se[[1]] +
  plots$ss[[1]] +
  plot_layout(
    design = layout, 
    guides = "collect"
  ) +
  plot_annotation()
p
```

### Spatial model

```{r}
plot_dat <- multivariate |> 
  filter(model_type == "mcmc_mean") |> 
  select(station, type = term, estimate) |> 
  pivot_wider(names_from = type, values_from = estimate) |> 
  ungroup() |> 
  select(-station) |> 
  correlate(method = "pearson", use = "pairwise.complete.obs", quiet = T) |> 
  pivot_longer(c(-term), names_to = "term2", values_to = "correlation") |> 
  inner_join(
    neighbor_types,
    by = c("term2" = "type")
  )

max_cor <- max(plot_dat$correlation, na.rm = T)
min_cor <- min(plot_dat$correlation, na.rm = T)
scale_size <- max(abs(max_cor), abs(min_cor), na.rm = T)
limits <- c(-1, 1) * scale_size




plots <- plot_dat |> 
  mutate(type = term) |> 
  group_by(type) |> 
  group_nest() |> 
  mutate(
    plots = map(data, 
                function(data, ...) {
                  data |> 
                    ggplot(aes(diff_x, diff_y, fill = correlation)) +
                    geom_raster() +
                    # scale_fill_viridis_c(guide = guide_colorbar(), limits = limits) +
                    scale_fill_distiller(
                      type = "div", 
                      palette = "RdBu", 
                      limits = limits,
                      direction = 1
                    ) +
                    facet_wrap("term") +
                    theme_void() 
                }
    )
  ) |> 
  select(type, plots) |> 
  pivot_wider(names_from = type, values_from = plots)


layout <- "
##A##
#BCD#
EF#GH
#IJK#
##L##
"


p <- plots$nn[[1]] + 
  plots$nw[[1]] + plots$n[[1]] + plots$ne[[1]] +
  plots$ww[[1]] + plots$w[[1]] + plots$e[[1]] + plots$ee[[1]] +
  plots$sw[[1]] + plots$s[[1]] + plots$se[[1]] +
  plots$ss[[1]] +
  plot_layout(
    design = layout, 
    guides = "collect"
  ) +
  plot_annotation()
p
```


# One at a time

```{r , eval=FALSE}
#| eval: false
results <- dat |> 
  select(-neighbor) |> 
  # pivot_wider(names_from = type, values_from = x) |> 
  group_by(station, model_type, type) |> 
  group_modify(
    function(data, ...) {
      
      lm(y ~ x - 1, data = data) |> 
        tidy()
    }
  ) |> 
  ungroup()

results |> 
  write_parquet("Data/univariate.parquet")
```

```{r}
univariate <- read_parquet("Data/univariate.parquet")
```


## Mean values

```{r}
plot_dat <- univariate |> 
  select(station, model_type, type, estimate) |> 
  summarise(
    mean = mean(estimate),
    sd = sd(estimate),
    .by = c(type, model_type)
  ) |> 
  inner_join(
    neighbor_types,
    by = "type"
  ) 

max_est <- max(plot_dat$mean, na.rm = T)
min_est <- min(plot_dat$mean, na.rm = T)
scale_size <- max(abs(max_est), abs(min_est), na.rm = T)
limits <- c(0, 1) * scale_size


plot_dat |> 
  ggplot(aes(diff_x, diff_y, fill = mean)) +
  geom_raster() + 
  # scale_fill_distiller(type = "div", palette = "RdBu", limits = limits, direction = 1) +
  scale_fill_viridis_c(limits = limits) +
  facet_wrap("model_type")
```

```{r}
plot_dat |> 
  select(-sd) |> 
  pivot_wider(names_from = model_type, values_from = mean) |> 
  ggplot(aes(mcmc_mean, ml_estimate)) +
  geom_abline(intercept = 0, slope = 1, lty = 2) +
  geom_point() +
  labs(
    x = "Neighour effect from spatial model",
    y = "Neighbour effect from ML model",
    title = "Comparison of neighbour effects in ML and MCMC models"
  )
```

```{r}
plot_dat |> 
  select(-mean) |> 
  pivot_wider(names_from = model_type, values_from = sd) |> 
  ggplot(aes(mcmc_mean, ml_estimate)) +
  geom_abline(intercept = 0, slope = 1, lty = 2) +
  geom_point() +
  coord_cartesian(xlim = c(0.15, 0.3), ylim = c(0.15, 0.3)) +
  labs(
    x = "Neighour effect from spatial model",
    y = "Neighbour effect from ML model",
    title = "Comparison of neighbour effects in ML and MCMC models"
  )
```

```{r}
univariate |> 
  select(station, model_type, type, estimate) |> 
  pivot_wider(names_from = model_type, values_from = estimate) |> 
  ggplot(aes(mcmc_mean, ml_estimate)) +
  geom_abline(intercept = 0, slope = 1, lty = 2) +
  geom_point() 
```


## Spatial Distribution

### Maximum Likelihood

```{r}
plot_dat <- univariate |> 
  filter(model_type == "ml_estimate") |> 
  select(station, type, estimate) |> 
  inner_join(
    stations,
    by = "station"
  )


max_est <- max(plot_dat$estimate, na.rm = T)
min_est <- min(plot_dat$estimate, na.rm = T)
scale_size <- max(abs(max_est), abs(min_est), na.rm = T)
limits <- c(0, 1) * scale_size

# plot_dat |>
#   filter(type == "ww") |>
#   ggplot(aes(proj_x, proj_y, fill = estimate)) +
#   geom_raster(interpolate = TRUE) +
#   scale_fill_distiller(type = "div", palette = "RdBu", limits = limits) +
#   facet_wrap("type")

plots <- plot_dat |> 
  mutate(term = type) |> 
  group_by(type) |> 
  group_nest() |> 
  mutate(
    plots = map(data, 
                function(data, ...) {
                  data |> 
                    ggplot(aes(proj_x, proj_y, fill = estimate)) +
                    geom_raster(interpolate = TRUE) +
                    # scale_fill_distiller(
                    #   type = "div",
                    #   palette = "RdBu",
                    #   limits = limits,
                    #   direction = 1
                    # ) +
                    scale_fill_viridis_c(limits = limits) +
                    facet_wrap("term") +
                    theme_void()
                }
    )
  ) |> 
  select(type, plots) |> 
  pivot_wider(names_from = type, values_from = plots)

layout <- "
##A##
#BCD#
EF#GH
#IJK#
##L##
"


p <- plots$nn[[1]] + 
  plots$nw[[1]] + plots$n[[1]] + plots$ne[[1]] +
  plots$ww[[1]] + plots$w[[1]] + plots$e[[1]] + plots$ee[[1]] +
  plots$sw[[1]] + plots$s[[1]] + plots$se[[1]] +
  plots$ss[[1]] +
  plot_layout(
    design = layout, 
    guides = "collect"
  ) +
  plot_annotation()
p
```

### Spatial Model

```{r}
plot_dat <- univariate |> 
  filter(model_type == "mcmc_mean") |> 
  select(station, type, estimate) |> 
  inner_join(
    stations,
    by = "station"
  )


max_est <- max(plot_dat$estimate, na.rm = T)
min_est <- min(plot_dat$estimate, na.rm = T)
scale_size <- max(abs(max_est), abs(min_est), na.rm = T)
limits <- c(0, 1) * scale_size

# plot_dat |>
#   filter(type == "ww") |>
#   ggplot(aes(proj_x, proj_y, fill = estimate)) +
#   geom_raster(interpolate = TRUE) +
#   scale_fill_distiller(type = "div", palette = "RdBu", limits = limits) +
#   facet_wrap("type")

plots <- plot_dat |> 
  mutate(term = type) |> 
  group_by(type) |> 
  group_nest() |> 
  mutate(
    plots = map(data, 
                function(data, ...) {
                  data |> 
                    ggplot(aes(proj_x, proj_y, fill = estimate)) +
                    geom_raster(interpolate = TRUE) +
                    # scale_fill_distiller(
                    #   type = "div",
                    #   palette = "RdBu",
                    #   limits = limits,
                    #   direction = 1
                    # ) +
                    scale_fill_viridis_c(limits = limits) +
                    facet_wrap("term") +
                    theme_void()
                }
    )
  ) |> 
  select(type, plots) |> 
  pivot_wider(names_from = type, values_from = plots)

layout <- "
##A##
#BCD#
EF#GH
#IJK#
##L##
"


p <- plots$nn[[1]] + 
  plots$nw[[1]] + plots$n[[1]] + plots$ne[[1]] +
  plots$ww[[1]] + plots$w[[1]] + plots$e[[1]] + plots$ee[[1]] +
  plots$sw[[1]] + plots$s[[1]] + plots$se[[1]] +
  plots$ss[[1]] +
  plot_layout(
    design = layout, 
    guides = "collect"
  ) +
  plot_annotation()
p
```

## Parameter Correlations

### Maximum Likelihood

```{r}
plot_dat <- univariate |> 
  filter(model_type == "ml_estimate") |> 
  select(station, type, estimate) |> 
  pivot_wider(names_from = type, values_from = estimate) |> 
  ungroup() |> 
  select(-station) |> 
  correlate(method = "pearson", use = "pairwise.complete.obs", quiet = T) |> 
  pivot_longer(c(-term), names_to = "term2", values_to = "correlation") |> 
  inner_join(
    neighbor_types,
    by = c("term2" = "type")
  )

max_cor <- max(plot_dat$correlation, na.rm = T)
min_cor <- min(plot_dat$correlation, na.rm = T)
scale_size <- max(abs(max_cor), abs(min_cor), na.rm = T)
limits <- c(0, 1) * scale_size




plots <- plot_dat |> 
  mutate(type = term) |> 
  group_by(type) |> 
  group_nest() |> 
  mutate(
    plots = map(data, 
                function(data, ...) {
                  data |> 
                    ggplot(aes(diff_x, diff_y, fill = correlation)) +
                    geom_raster() +
                    # scale_fill_viridis_c(guide = guide_colorbar(), limits = limits) +
                    # scale_fill_distiller(
                    #   type = "div", 
                    #   palette = "RdBu", 
                    #   limits = limits,
                    #   direction = 1
                    # ) +
                    scale_fill_viridis_c(limits = limits) +
                    facet_wrap("term") +
                    theme_void() 
                }
    )
  ) |> 
  select(type, plots) |> 
  pivot_wider(names_from = type, values_from = plots)


layout <- "
##A##
#BCD#
EF#GH
#IJK#
##L##
"


p <- plots$nn[[1]] + 
  plots$nw[[1]] + plots$n[[1]] + plots$ne[[1]] +
  plots$ww[[1]] + plots$w[[1]] + plots$e[[1]] + plots$ee[[1]] +
  plots$sw[[1]] + plots$s[[1]] + plots$se[[1]] +
  plots$ss[[1]] +
  plot_layout(
    design = layout, 
    guides = "collect"
  ) +
  plot_annotation()
p
```

### Spatial model

```{r}
plot_dat <- univariate |> 
  filter(model_type == "mcmc_mean") |> 
  select(station, type, estimate) |> 
  pivot_wider(names_from = type, values_from = estimate) |> 
  ungroup() |> 
  select(-station) |> 
  correlate(method = "pearson", use = "pairwise.complete.obs", quiet = T) |> 
  pivot_longer(c(-term), names_to = "term2", values_to = "correlation") |> 
  inner_join(
    neighbor_types,
    by = c("term2" = "type")
  )

max_cor <- max(plot_dat$correlation, na.rm = T)
min_cor <- min(plot_dat$correlation, na.rm = T)
scale_size <- max(abs(max_cor), abs(min_cor), na.rm = T)
limits <- c(0, 1) * scale_size




plots <- plot_dat |> 
  mutate(type = term) |> 
  group_by(type) |> 
  group_nest() |> 
  mutate(
    plots = map(data, 
                function(data, ...) {
                  data |> 
                    ggplot(aes(diff_x, diff_y, fill = correlation)) +
                    geom_raster() +
                    # scale_fill_viridis_c(guide = guide_colorbar(), limits = limits) +
                    # scale_fill_distiller(
                    #   type = "div", 
                    #   palette = "RdBu", 
                    #   limits = limits,
                    #   direction = 1
                    # ) +
                    scale_fill_viridis_c(limits = limits) +
                    facet_wrap("term") +
                    theme_void() 
                }
    )
  ) |> 
  select(type, plots) |> 
  pivot_wider(names_from = type, values_from = plots)


layout <- "
##A##
#BCD#
EF#GH
#IJK#
##L##
"


p <- plots$nn[[1]] + 
  plots$nw[[1]] + plots$n[[1]] + plots$ne[[1]] +
  plots$ww[[1]] + plots$w[[1]] + plots$e[[1]] + plots$ee[[1]] +
  plots$sw[[1]] + plots$s[[1]] + plots$se[[1]] +
  plots$ss[[1]] +
  plot_layout(
    design = layout, 
    guides = "collect"
  ) +
  plot_annotation()
p
```

### Outcome Correlation

```{r}
dat |> 
  filter(model_type == "ml_estimate") |> 
  select(y, x, type) |> 
  pivot_wider(names_from = type, values_from = x) |> 
  correlate(method = "pearson", use = "pairwise.complete.obs", quiet = T) |> 
  pivot_longer(c(-term), names_to = "term2", values_to = "correlation") |> 
  # filter(term == "y") |> 
  inner_join(
    neighbor_types,
    by = c("term2" = "type")
  ) |>
  ggplot(aes(diff_x, diff_y, fill = correlation)) +
  geom_raster() +
  scale_fill_viridis_c() +
  facet_wrap("term")
```

# Comparing predictions

```{r}
plot_dat <- d |> 
  pivot_wider(names_from = model_type, values_from = t_val) |> 
  mutate(
    diff = ml_estimate - mcmc_mean,
    abs_diff = abs(diff),
    time = as.numeric(as.factor(year)),
    period = case_when(
      year <= 2000 ~ "Period 1",
      year <= 2040 ~ "Period 2",
      TRUE ~ "Period 3"
    )
  )

max_est <- max(plot_dat$abs_diff, na.rm = T)
min_est <- min(plot_dat$abs_diff, na.rm = T)
scale_size <- max(abs(max_est), abs(min_est), na.rm = T)
limits <- c(-1, 1) * scale_size

plot_dat |> 
  ggplot(aes(time, station, fill = diff)) +
  geom_raster() +
  scale_fill_distiller(
    type = "div", palette = "RdBu", limits = limits,
  ) +
  scale_fill_viridis_c(limits = limits) +
  coord_cartesian(expand = FALSE)
```



```{r}
plot_dat |> 
  select(year, station, mcmc_mean, ml_estimate, diff, abs_diff) |> 
  group_by(year) |> 
  summarise(
    value = mean(diff)
  ) |> 
  ggplot(aes(year, value)) +
  geom_hline(yintercept = 0, lty = 2, alpha = 0.3) +
  geom_point() +
  geom_segment(
    aes(yend = 0, xend = year),
    lty = 2, 
    alpha = 0.5
  ) +
  scale_x_continuous(
    breaks = c(
      1980, 2000,
      2020, 2040,
      2060, 2080
    )
  )
```

```{r}
plot_dat <- d |> 
  pivot_wider(
    names_from = model_type, values_from = t_val
  ) |> 
  mutate(diff = ml_estimate - mcmc_mean) |> 
  group_by(station) |> 
  summarise(
    value = mean(diff)
  ) |> 
  inner_join(
    stations,
    by = "station"
  ) 

max_est <- max(plot_dat$value, na.rm = T)
min_est <- min(plot_dat$value, na.rm = T)
scale_size <- max(abs(max_est), abs(min_est), na.rm = T)
limits <- c(-1, 1) * scale_size

plot_dat |> 
  ggplot(aes(proj_x, proj_y, fill = value)) +
  geom_raster() +
  scale_fill_distiller(limits = limits, type = "div", palette = "RdBu") +
  coord_cartesian(expand = FALSE)
```

