---
title: "basics"
output: rmarkdown::html_vignette
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
#| eval: false
library(tidyverse)
library(progressr)
library(future)
library(bayesplot)
# devtools::load_all()
library(bggjphd)
library(GGally)
library(scales)
library(cowplot)


```


```{r}
if (!file.exists("results.rds")) {
  n_iter <- 4000
  plan(multisession, workers = 4)
  with_progress({
    results <- ms_smooth(n_samp = n_iter)
  })
  plan(sequential)
  write_rds(results, "results.rds")
} else {
  results <- read_rds("results.rds")
  n_iter <- results |> pull(.iteration) |> max()
}
```

```{r}
results |> 
  filter(.iteration > n_iter/2) |> 
  subset_draws(
    c("mu_psi", "mu_phi", "mu_tau", "mu_gamma", "theta"), 
  ) |> 
  summarise_draws()
```



```{r}
results |> 
  filter(.iteration > n_iter/2) |>
  subset_draws("theta") |> 
  mcmc_trace()
```

```{r}
results |> 
  subset_draws("theta[1]") |> 
  as_tibble() |> 
  rename(value = "theta[1]") |> 
  group_by(.chain) |> 
  mutate(accept = 1 * (value != lag(value))) |> 
  ungroup() |> 
  ggplot(aes(.iteration, accept, group = .chain)) +
  geom_smooth(method = "loess", span = 0.3, se = 0)
```


```{r}
if (!file.exists("station_mcmc_ml.rds")) {
  
  plot_dat <- results |> 
    filter(.iteration > n_iter/2) |> 
    subset_draws(
      c("psi", "tau", "phi", "gamma")
    ) |> 
    summarise_draws()
  
  plot_dat |> 
    select(variable, mcmc_mean = mean, mcmc_median = median) |> 
    mutate(station = parse_number(variable),
           variable = str_replace(variable, "\\[.*$", "")) |> 
    inner_join(
      stations,
      by = "station"
    ) |> 
    inner_join(
      station_estimates |> 
        select(station, par) |> 
        unnest(par) |> 
        rename(ml_estimate = value, variable = name),
      by = c("station", "variable")
    ) |> 
    select(station, proj_x, proj_y, latitude, longitude, variable, ml_estimate, mcmc_mean) |> 
    write_rds(file = "station_mcmc_ml.rds")
}

plot_dat <- read_rds("station_mcmc_ml.rds")
```

